require:
  - rubocop-performance
  - rubocop-rails

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 40

Metrics/BlockNesting:
  Max: 4

Metrics/ParameterLists:
  Max: 4

Metrics/PerceivedComplexity:
  Max: 8

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/LineLength:
  Enabled: true
  Max: 120

Layout/IndentationWidth:
  Enabled: true
  Width: 4

Layout/ArrayAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false
